version: '3'

services:
  web:
    container_name: web
    image: webcast-web:latest
    expose:
      - 80
      - 8080
      - 22
      - 5140
    networks:
      - net

  rtmp:
    container_name: rtmp
    image: webcast-rtmp:latest
    depends_on:
      - web
    expose:
      - 1935
      - 8080
      - 22
      - 5140
    networks:
      - net
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined

  loadbalancer:
    container_name: loadbalancer
    image: webcast-haproxy:latest
    depends_on:
      - web
      - rtmp
    environment:
      - BALANCE=leastconn
    ports:
      - 80:80
      - 1935:1935
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge
