version: '3'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: dockerfile
    image: webcast-web:latest
    expose:
      - 80
    networks:
      - net
    volumes:
      - shared:/tmp

  rtmp:
    container_name: rtmp
    build:
      context: ./rtmp
      dockerfile: dockerfile
    image: webcast-rtmp:latest
    expose:
      - 1935
      - 8080
    networks:
      - net
    volumes:
      - shared:/tmp

  loadbalancer:
    container_name: loadbalancer
    build:
      context: ./haproxy
      dockerfile: dockerfile
    image: webcast-haproxy:latest
    depends_on:
      - web
      - rtmp
      - grafana
    environment:
      - BALANCE=leastconn
    ports:
      - 80:80
      - 1935:1935
      - 1936:1936
      - 8080:8080
      - 3000:3000
    networks:
      - net

  loki:
    image: grafana/loki:latest
    command: -config.file=/configs/loki.yaml
    depends_on:
      - promtail
    expose:
      - 3100
    volumes:
      - configs:/configs
    networks:
      - net

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/configs/promtail.yaml
    volumes:
      - configs:/configs
      - shared:/tmp
    networks:
      - net

  grafana:
    image: grafana/grafana:master
    depends_on:
      - loki
    expose:
      - 3000
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/tmp/shared"
  configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/tmp/configs"
