server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: stream-logs
    entry_parser: raw

    static_configs:
    - targets:
        - localhost
      labels:
        job: stream-logs
        __path__: /tmp/stream.log
    - targets:
        - localhost
      labels:
        job: stream-num
        __path__: /tmp/stream.log
    - targets:
        - localhost
      labels:
        job: stream-ip
        __path__: /tmp/stream.log

    pipeline_stages:
    - match:
        selector: '{job="stream-num"}'
        stages:
        - regex:
            expression: '^.* (?P<num_conn>.*)$'
        - output:
            source: num_conn
    - match:
        selector: '{job="stream-ip"}'
        stages:
        - regex:
            expression: '^(?P<ip_addr>.*) - - .*'
        - labels:
            ip_addr:
        - output:
            source: ip_addr
