FROM tiangolo/nginx-rtmp

RUN apt update
RUN apt install -y \
        ffmpeg \
        tree

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir /tmp/rec/
RUN chown -R www-data:root /tmp/rec/ && chmod o+x /tmp/rec/
