FROM tiangolo/nginx-rtmp

RUN apt update
RUN apt install -y \
        ffmpeg \
        tree

RUN mkdir -p /var/www/rec /var/www/video /var/www/audio

COPY nginx.conf /etc/nginx/nginx.conf
COPY player.html /var/www/player.html

RUN chown -R www-data:www-data /var/www/ && chmod -R o+x /var/www/
