FROM tiangolo/nginx-rtmp

RUN apt update
RUN apt install -y \
        ffmpeg \
        tree

RUN mkdir -p /var/www/video /var/www/audio /tmp/stream/rec/video /tmp/stream/rec/audio

COPY stat.xsl /usr/local/nginx/html/stat.xsl
COPY nginx.conf /etc/nginx/nginx.conf
COPY player.html /var/www/player.html

RUN chown -R www-data:www-data /tmp/stream/ && chmod -R o+x /tmp/stream/
RUN chown -R www-data:www-data /var/www/ && chmod -R o+x /var/www/
