FROM tiangolo/nginx-rtmp

RUN apt update
RUN apt install -y \
        ffmpeg \
        tree \
        openssh-server

COPY stat.xsl /usr/local/nginx/html/stat.xsl
COPY nginx.conf /etc/nginx/nginx.conf
COPY player.html /var/www/player.html

COPY restricted.pass /etc/restricted.pass
COPY admin.pass /etc/admin.pass

RUN useradd -ms /bin/bash stream -g www-data && \
  mkdir -p /home/stream/.ssh/ /home/stream/media/stream /home/stream/logs \
    /home/stream/media/rec_video /home/stream/media/rec_audio \
    /home/stream/media/video /home/stream/media/audio && \
    chmod -R 755 /home/stream/media
COPY id_rsa.pub /home/stream/.ssh/
RUN cat /home/stream/.ssh/id_rsa.pub >> /home/stream/.ssh/authorized_keys && \
  chmod 700 /home/stream/.ssh && \
  chmod 400 /home/stream/.ssh/authorized_keys && \
  chmod 400 /home/stream/.ssh/id_rsa.pub && \
  chown -R stream:www-data /home/stream/

RUN chown -R stream:www-data /var/www/ && chmod -R o+x /var/www/ && \
  chown -R root:www-data /var/log/nginx/

COPY ./cmd.sh /usr/local/bin/cmd.sh
RUN chmod 755 /usr/local/bin/cmd.sh
CMD /usr/local/bin/cmd.sh
