FROM rtmp-nginx-20.04:latest

RUN apt update && \
  apt upgrade -y && \
  apt install -y \
        ffmpeg \
        syslog-ng \
        tree \
        openssh-server \
        sqlite3 \
        python3 

COPY stat.xsl /usr/local/nginx/html/stat.xsl
COPY nginx.conf /etc/nginx/nginx.conf
COPY player.html /var/www/player.html

# Create a place to put streaming and recorded video and audio
RUN useradd -ms /bin/bash stream -g www-data && \
  mkdir -p /home/stream/.ssh/ /home/stream/media/stream /home/stream/logs \
    /home/stream/media/rec_video /home/stream/media/rec_audio \
    /home/stream/media/video /home/stream/media/audio && \
    chmod -R 755 /home/stream/media
# Put the public key used by sshfs to transfer the files from `rtmp` to `web`
COPY id_rsa.pub /home/stream/.ssh/
RUN cat /home/stream/.ssh/id_rsa.pub >> /home/stream/.ssh/authorized_keys && \
  chmod 700 /home/stream/.ssh && \
  chmod 400 /home/stream/.ssh/authorized_keys && \
  chmod 400 /home/stream/.ssh/id_rsa.pub && \
  chown -R stream:www-data /home/stream/

# Make sure that directories have the right permissions for file storage and handling
RUN chown -R stream:www-data /var/www/ && chmod -R o+x /var/www/ && \
  chown -R root:www-data /var/log/nginx/

# Setup syslog
COPY syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
RUN mkdir -p /var/log/syslog-ng

# Copy DB handling files
COPY parse_db.py /usr/local/db/parse_db.py 

# Docker cmd to run on startup
# Starts syslog, ssh, and nginx
# A general rule is to have one service per container. 
# However, it's easier and more cost effective to have all the services in one place.
COPY ./cmd.sh /usr/local/bin/cmd.sh
RUN chmod 755 /usr/local/bin/cmd.sh
CMD /usr/local/bin/cmd.sh
